language: node_js
sudo: required
node_js:
    - "6"
install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get install libstdc++6 -y
    - sudo apt-get install gcc -y
    - sudo apt-get install g++ -y
    - npm install
    - sh buildtests.sh
script:
    npm test


