language: node_js
sudo: required
node_js:
    - "6"
install:
    - sh install.sh
    - sh buildtests.sh
    - ./scripts/travis.sh
script:
    npm test

notifications:
    slack: zehbelab:BuLG0b1qhVzAyihGf2XbQU4D
