language: node_js
sudo: required
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - xvfb
    - g++-5
    - fakeroot
    - gtk2.0
    - rpm
before_install:
- npm install -g greenkeeper-lockfile
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- bash scripts/install.bash
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
script:
- npm test
- bash scripts/cleanTests.bash
- bash scripts/prepareLinuxRelease.bash
notifications:
  slack: zehbelab:BuLG0b1qhVzAyihGf2XbQU4D
deploy:
  provider: releases
  api_key:
  - secure: "DfPPDQCPT+v+nFHcMJV618eybEpSdt1W4ewHjSRhKqIEWmOIVh6D7NB8adKHJUCBiz4LuJgrZtm+xQrlw3ysTeSP45lvJgrNLj7BF8t8wxy0CewK3CJkpGJQmy2J+BROjFTXWyDH/hIig9L5w0b+odaQDSTMu3AA+xczYuAFn60kWXPlbQVhxFNlAQK5KvAZe66BxMarjZl3WvvnYHVsM0appiE5eIypdS+WOPMXPK56WKmHQ9ECNGErw9GIfasdsXAtSIFD7RThoaw96qzvkCVcW+CRbVC4sCnZYS4xZy/JbXvFopi/coE9rCKNH3jbIC2v1PI09RxhD7l4Sv2nLboELSPRjBw4WWBboybrLVApYsBD+AuTlwbVLyVKToT24tfwBAqYnDfIsWOHdblZvOOkLKss7hCfGlQxHZRjyqiMwQmxDuZyK3No8XE5hlV2md61u+/popWxzzWShl/ckZeIiSW1I66a0wBBcnDjh9CX+Qx3BNFTL9yJiAFPjh5xd/2/4x7tOIdvTNvW8mBEY2ADS02W2RHIrAUyxjxZew2cUE7jbt6zdSOm4XIPtNytXj8QdlF+bfw0g4gfRgvuQrNCBLqHgu12KilSVsFWt3dGG/THuTw8/BtcvzVi119ygnfHHBe5XdZmbWBi75EjrauSSqBLzkUb8EIzAnJ7VJw="
  file_glob: true
  file:
  - phat-linux-x64-portable.tar.gz
  - phat-linux-x64-update-full.tar.gz
  - phat-linux-x64-update-diff.tar.gz
  - phat-linux-x64-update.tar.gz
  - phat*.deb
  - phat*.rpm
  skip_cleanup: true
  on:
    repo: chgibb/PHAT
    tags: true
env:
  global:
    secure: lunzLyHUDHN7LILMgnnpAFt2tMgpiBGUg53CJ6t9WEoG80jj9jqeQIqRwEc4x/1oGXmWxnx+W7JOdsaI+TC9ukXtTq9gs1aO8SUXimF1KFxkHJyMXM4HxWzK0L6L/YS2a4eObqnID7QfFeFzeGKmw21NuiLa1yopLkF4SaIwngmpb/fqLxsrQefHCD17Fk5ZH1OYnnAXRPMPF9DcsLgGL+yqeL4Gj9V3GoiOwJxY+bC25DszS27w2dEU5XcydJrlwIpwYeX9sTZuPRXTvtR/He/STnKCia6DGByY9emcbZIVoii++MO93p2hs8O4zNWgzxM6iviG0T3lBuq0LwZzgUclW8/H2MAdvRTxIjblZS4NBan3rJIaw3EGlIUgr5Nkl61Lr6B3hhlB6SKoaN0zraAsLpRuewutQQG6YbBToPMLfkvBZ1WwBlyyGXi6fRSey4hlYYFJhcJyycXOoPdKXcjQjI+U8uHmVCKlcMH8tD8ZBe2ez4iYikpvQ8LZZHpryVSKrNdPlCr2rd2yQTmqlU+fe5G6+k4lh/ua9fMhAGlKvcXCbzRSFWnlrEXj0DJHvBoNZDUnGAJG9XvefqUgzsSBCN6jmCGLJju66GgwOI4jOaj8tOqX0BDyei9fjwYnQ58gtZcUpRKVHhuC0spOIyYWqPcEzA9tgf9t/SWG66Q=
