install:
  - C:\cygwin\bin\bash.exe scripts/install.bash

build_script:
  - C:\cygwin\bin\bash.exe scripts/buildtests.bash

test_script:
  - C:\cygwin\bin\bash.exe scripts/runtests.bash

clone_depth: 1

environment:
  OSTYPE: 'cygwin'
  APPVEYOR: true