install:
  - ps: wget "https://github.com/icsharpcode/SharpZipLib/releases/download/0.86.0.518/ICSharpCode.SharpZipLib.dll" -OutFile "src/installUpdateProcess/ICSharpCode.SharpZipLib.dll"
  - bash scripts/install.bash

build_script:
  - bash scripts/build.bash

test_script:
 

clone_depth: 1

environment:
  OSTYPE: 'cygwin'
  APPVEYOR: true