clone_depth: 10
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node ''
  - ps: wget "https://github.com/icsharpcode/SharpZipLib/releases/download/0.86.0.518/ICSharpCode.SharpZipLib.dll" -OutFile "src/installUpdateProcess/ICSharpCode.SharpZipLib.dll"
  - ps: wget "https://github.com/chgibb/FastQC0.11.5/releases/download/v0.11.5/FastQC.tar.gz" -OutFile "FastQC.tar.gz"
  - bash scripts/install.bash >nul

build_script:
  - bash scripts/build.bash

test_script:
 - bash scripts/buildtests.bash
 - npm test
 - bash scripts/cleanTests.bash
 - bash scripts/prepareWindowsRelease.bash

artifacts:
  - path: phat-win32-x64-update.tar.gz
    name: to-publish

  - path: phat-win32-x64-setup.exe
    name: to-publish

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: fqX7hM2PGofEbimvGZVHX3VfHeKE+IFOQUOH/W96SWtmZNG+nUgou9zbCt6RA5j9
  artifact: to-publish
  on:
    appveyor_repo_tag: true

environment:
  OSTYPE: 'cygwin'
  APPVEYOR: true
  appveyor_rdp_password:
    secure: HZDsRPdDWdN+s9VcHAXIyA==

notifications:
  - provider: Slack
    auth_token:
      secure: 2zd4D6OQUJjTftAUfwSgCoBboxGMc0Fi4zS1FHZNx4lPz3WlKpx3qJThpfApNPg2Mo9sIkXCVJiJ/bZOGD/X4SwrDw5xEOOVIWv1pw+P8Qg=
    channel: '#updates'
