clone_depth: 10
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: Install-Product node ''
  - ps: wget "https://github.com/icsharpcode/SharpZipLib/releases/download/0.86.0.518/ICSharpCode.SharpZipLib.dll" -OutFile "src/installUpdateProcess/ICSharpCode.SharpZipLib.dll"
  - ps: wget "https://github.com/chgibb/FastQC0.11.5/releases/download/v0.11.5/FastQC.tar.gz" -OutFile "FastQC.tar.gz"
  - ps: wget "https://github.com/chgibb/pileup.js/releases/download/v0.6.8/pileup.js" -OutFile "forDist/pileup.js"
  - ps: wget "https://github.com/chgibb/pileup.js/releases/download/v0.6.8/pileup.css" -OutFile "forDist/styles/pileup.css"
  - ps: wget "https://github.com/dkoboldt/varscan/releases/download/2.4.2/VarScan.v2.4.2.jar" -OutFile "forDist/varscan.jar"
  - ps: wget "https://github.com/samtools/samtools/releases/download/1.4.1/samtools-1.4.1.tar.bz2" -OutFile "samtools-1.4.1.tar.bz2"
  - bash scripts/install.bash >nul

build_script:
  - bash scripts/build.bash

test_script:
 - bash scripts/buildtests.bash
 - npm test
 - bash scripts/cleanTests.bash
 - bash scripts/prepareWindowsRelease.bash

artifacts:
  - path: phat-win32-x64-update-full.tar.gz
    name: to-publish

  - path: phat-win32-x64-update-diff.tar.gz
    name: to-publish

  - path: phat-win32-x64-update.tar.gz
    name: to-publish

  - path: phat-win32-x64-setup.exe
    name: to-publish

  - path: phat-win32-x64-portable.zip
    name: to-publish

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: fqX7hM2PGofEbimvGZVHX3VfHeKE+IFOQUOH/W96SWtmZNG+nUgou9zbCt6RA5j9
  artifact: to-publish
  on:
    appveyor_repo_tag: true

environment:
  OSTYPE: 'cygwin'
  APPVEYOR: true
  APPVEYOR_RDP_PASSWORD:
    secure: vR9G9F+rHt8aGtofqsoRh2blpRC8Dy1yd1OtN7LvE18=
  GH_TOKEN_APPVEYOR:
    secure: V1YRM+jKAfr0DIpI8p2fKBarTpEbAFx6VuFznHtIyaLpnBg5nieoP//BxqkWZ4SK

notifications:
  - provider: Slack
    auth_token:
      secure: 2zd4D6OQUJjTftAUfwSgCoBboxGMc0Fi4zS1FHZNx4lPz3WlKpx3qJThpfApNPg2Mo9sIkXCVJiJ/bZOGD/X4SwrDw5xEOOVIWv1pw+P8Qg=
    channel: '#updates'
