clone_depth: 1

install:
  - ps: Install-Product node ''
  - ps: wget "https://github.com/icsharpcode/SharpZipLib/releases/download/0.86.0.518/ICSharpCode.SharpZipLib.dll" -OutFile "src/installUpdateProcess/ICSharpCode.SharpZipLib.dll"
  - ps: wget "https://github.com/chgibb/FastQC0.11.5/releases/download/v0.11.5/FastQC.tar.gz" -OutFile "FastQC.tar.gz"
  - bash scripts/install.bash

build_script:
  - bash scripts/build.bash

test_script:
 - bash scripts/buildtests.bash
 - npm test
 - bash scripts/cleanTests.bash

artifacts:
  - path: '\*.tar.gz'
  - path: '\*.exe'

before_deploy:
  - bash scripts/prepareWindowsRelease.bash

deploy:
  provider: GitHub
  force_update: true
  auth_token:
    secure: fqX7hM2PGofEbimvGZVHX3VfHeKE+IFOQUOH/W96SWtmZNG+nUgou9zbCt6RA5j9
  artifact: /.*\.gz|.*\.exe/
  on:
    appveyor_repo_tag: true

environment:
  OSTYPE: 'cygwin'
  APPVEYOR: true