/// <reference types="jest" />

import {evaluateCIGAR} from "./../lib/lib";

it(`should correctly extract CIGAR fragments 1`,() => {
    let res = evaluateCIGAR("ATCGATCGATCG","4M1I");

    expect(res).toBeDefined();

    expect(res!.length).toBe(1);
    expect(res![0]).toBe("A");
}); 

it(`should correctly extract CIGAR fragments 2`,() => {
    let res = evaluateCIGAR("AACACCTGCAGAAACTGGAGGGCATTTTACACTTTCATCATCCACTATTAGTACACATAATTATGAAGAAATTCCTATGGATACATTTATTGTTAGCACAAACCCTAACACAGTAACTAGTAGCACACCCATACCAGGGTCTCGCCCAGTG","151M");

    expect(res).toBeUndefined();
});

it(`should correctly extract CIGAR fragments 3`,() => {
    let res = evaluateCIGAR("CGATCTGAAACTAGTTTTATTGATGCTGGTGCACCAACATCTGTACCTTCCATTCCCCCAGATGTATCAGGATTTAGTATTACTACTTCAACTGATACCACACCTGCTATATTAGATATTAATAATACTGTTACTACTGTTACTACACATA","4M2I145M");

    expect(res).toBeDefined();

    expect(res!.length).toBe(1);
    expect(res![0]).toBe("CT");
});

it(`should correctly extract CIGAR fragments 4`,() => {
    let res = evaluateCIGAR("GAAACTAGTTTTATTGATGCTGGTGCACCAACATCTGTACCTTCCATTCCCCCAGATGTATCAGGATTTAGTATTACTACTTCAACTGATACCACACCTGCTATATTAGATATTAATAATACTGTTACTACTGTTACTACACATAAGATCG","146M1D5M");

    expect(res).toBeUndefined();
});

it(`should correctly extract CIGAR fragments 5`,() => {
    let res = evaluateCIGAR("GAAACTAGTTTTATTGATGCTGGTGCACCAACATCTGTACCTTCCATTCCCCCAGATGTATCAGGATTTAGTATTACTACTTCAACTGATACCACACCTGCTATATTAGATATTAATAATACTGTTACTACTGTTACTACACATAAGATCG","*");

    expect(res).toBeUndefined();
});

it(`should correctly extract CIGAR fragments 6`,() => {
    let res = evaluateCIGAR("GAAACTAGTTTTATTGATGCTGGTGCACCAACATCTGTACCTTCCATTCCCCCAGATGTATCAGGATTTAGTATTACTACTTCAACTGATACCACACCTGCTATATTAGATATTAATAATACTGTTACTACTGTTACTACACATAAGATCG","0");

    expect(res).toBeUndefined();
});

it(`should correctly extract CIGAR fragments 7`,() => {
    function evaluate()
    {
        evaluateCIGAR("CGATCTGAAACTAGTTTTATTGATGCTGGTGCACCAACATCTGTACCTTCCATTCCCCCAGATGTATCAGGATTTAGTATTACTACTTCAACTGATACCACACCTGCTATATTAGATATTAATAATACTGTTACTACTGTTACTACACAT","4M2I145M");
    }
    expect(evaluate).toThrow();

});